-- SchedulerX 调度系统数据库初始化脚本
-- 数据库: schedulerx
-- 创建时间: 2026-06-01

# USE schedulerx;

-- =============================================
-- 1. DAG 定义表
-- =============================================
CREATE TABLE IF NOT EXISTS sx_dag_def (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    dag_id VARCHAR(64) NOT NULL COMMENT 'DAG 业务标识',
    dag_name VARCHAR(128) NOT NULL COMMENT 'DAG 名称',
    owner VARCHAR(64) DEFAULT 'mdatax' COMMENT '所属系统',
    owner_ref_id VARCHAR(64) DEFAULT NULL COMMENT '业务方关联 ID',
    cron_expression VARCHAR(128) DEFAULT NULL COMMENT 'Quartz Cron 表达式',
    timezone VARCHAR(32) DEFAULT 'Asia/Shanghai' COMMENT '时区',
    timeout_seconds INT DEFAULT 3600 COMMENT 'DAG 整体超时（秒）',
    failure_strategy VARCHAR(16) DEFAULT 'STOP_ALL' COMMENT '失败策略：STOP_ALL / CONTINUE',
    max_retry_times INT DEFAULT 0 COMMENT '失败重试次数',
    retry_interval_seconds INT DEFAULT 0 COMMENT '重试间隔（秒）',
    status TINYINT DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
    description VARCHAR(512) DEFAULT NULL COMMENT '描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_dag_id (dag_id),
    INDEX idx_owner (owner),
    INDEX idx_status (status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DAG 定义表';

-- =============================================
-- 2. DAG 任务节点定义表
-- =============================================
CREATE TABLE IF NOT EXISTS sx_dag_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    dag_id VARCHAR(64) NOT NULL COMMENT '所属 DAG',
    task_id VARCHAR(64) NOT NULL COMMENT '任务节点标识',
    task_name VARCHAR(128) NOT NULL COMMENT '任务名称',
    task_type VARCHAR(16) DEFAULT 'HTTP_CALLBACK' COMMENT '任务类型：HTTP_CALLBACK / SHELL',
    task_config JSON DEFAULT NULL COMMENT '执行配置（URL、Method、Body、Header、超时）',
    upstream_tasks TEXT DEFAULT NULL COMMENT '上游任务 ID 列表，JSON 数组',
    retry_times INT DEFAULT 0 COMMENT '节点级重试次数',
    timeout_seconds INT DEFAULT 600 COMMENT '节点超时（秒）',
    priority INT DEFAULT 0 COMMENT '优先级（越小越高）',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_dag_task (dag_id, task_id),
    INDEX idx_dag_id (dag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DAG 任务节点定义表';

-- =============================================
-- 3. DAG 执行实例表
-- =============================================
CREATE TABLE IF NOT EXISTS sx_dag_instance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    instance_id VARCHAR(64) NOT NULL COMMENT '实例业务标识',
    dag_id VARCHAR(64) NOT NULL COMMENT '所属 DAG',
    trigger_type VARCHAR(16) DEFAULT 'MANUAL' COMMENT '触发类型：SCHEDULED / MANUAL / EVENT / RETRY',
    trigger_time DATETIME DEFAULT NULL COMMENT '计划触发时间',
    status VARCHAR(16) DEFAULT 'PENDING' COMMENT '状态：PENDING / RUNNING / SUCCESS / FAILURE / STOPPED / TIMEOUT',
    start_time DATETIME DEFAULT NULL COMMENT '实际开始时间',
    end_time DATETIME DEFAULT NULL COMMENT '结束时间',
    duration_ms INT DEFAULT NULL COMMENT '执行耗时（毫秒）',
    context JSON DEFAULT NULL COMMENT '运行时上下文',
    failure_task_id VARCHAR(64) DEFAULT NULL COMMENT '首个失败的任务 ID',
    retry_count INT DEFAULT 0 COMMENT '已重试次数',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_instance_id (instance_id),
    INDEX idx_dag_id (dag_id),
    INDEX idx_status (status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DAG 执行实例表';

-- =============================================
-- 4. 任务执行实例表
-- =============================================
CREATE TABLE IF NOT EXISTS sx_task_instance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    task_instance_id VARCHAR(64) NOT NULL COMMENT '任务实例标识',
    dag_instance_id VARCHAR(64) NOT NULL COMMENT '所属 DAG 实例',
    dag_id VARCHAR(64) NOT NULL COMMENT '所属 DAG',
    task_id VARCHAR(64) NOT NULL COMMENT '任务节点 ID',
    task_name VARCHAR(128) DEFAULT NULL COMMENT '任务名称',
    status VARCHAR(16) DEFAULT 'PENDING' COMMENT '状态：PENDING / WAITING_UPSTREAM / RUNNING / SUCCESS / FAILURE / TIMEOUT / SKIPPED',
    attempt_number INT DEFAULT 1 COMMENT '当前尝试次数',
    start_time DATETIME DEFAULT NULL COMMENT '开始时间',
    end_time DATETIME DEFAULT NULL COMMENT '结束时间',
    duration_ms INT DEFAULT NULL COMMENT '耗时（毫秒）',
    callback_url VARCHAR(512) DEFAULT NULL COMMENT '回调地址',
    request_body TEXT DEFAULT NULL COMMENT '发送给执行方的请求体',
    response_body TEXT DEFAULT NULL COMMENT '执行方返回的响应',
    output JSON DEFAULT NULL COMMENT '执行输出',
    error_msg TEXT DEFAULT NULL COMMENT '错误信息',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_task_instance_id (task_instance_id),
    INDEX idx_dag_instance_id (dag_instance_id),
    INDEX idx_dag_id (dag_id),
    INDEX idx_status (status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行实例表';

-- =============================================
-- 5. Quartz 调度表（表前缀 sx_qrtz_）
-- =============================================
DROP TABLE IF EXISTS sx_qrtz_fired_triggers;
DROP TABLE IF EXISTS sx_qrtz_paused_trigger_grps;
DROP TABLE IF EXISTS sx_qrtz_scheduler_state;
DROP TABLE IF EXISTS sx_qrtz_locks;
DROP TABLE IF EXISTS sx_qrtz_simple_triggers;
DROP TABLE IF EXISTS sx_qrtz_simprop_triggers;
DROP TABLE IF EXISTS sx_qrtz_cron_triggers;
DROP TABLE IF EXISTS sx_qrtz_blob_triggers;
DROP TABLE IF EXISTS sx_qrtz_triggers;
DROP TABLE IF EXISTS sx_qrtz_job_details;
DROP TABLE IF EXISTS sx_qrtz_calendars;

CREATE TABLE sx_qrtz_job_details (
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  JOB_CLASS_NAME VARCHAR(250) NOT NULL,
  IS_DURABLE VARCHAR(1) NOT NULL,
  IS_NONCONCURRENT VARCHAR(1) NOT NULL,
  IS_UPDATE_DATA VARCHAR(1) NOT NULL,
  REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_triggers (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  NEXT_FIRE_TIME BIGINT(13) NULL,
  PREV_FIRE_TIME BIGINT(13) NULL,
  PRIORITY INTEGER NULL,
  TRIGGER_STATE VARCHAR(16) NOT NULL,
  TRIGGER_TYPE VARCHAR(8) NOT NULL,
  START_TIME BIGINT(13) NOT NULL,
  END_TIME BIGINT(13) NULL,
  CALENDAR_NAME VARCHAR(200) NULL,
  MISFIRE_INSTR SMALLINT(2) NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
    REFERENCES sx_qrtz_job_details(SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_simple_triggers (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  REPEAT_COUNT BIGINT(7) NOT NULL,
  REPEAT_INTERVAL BIGINT(12) NOT NULL,
  TIMES_TRIGGERED BIGINT(10) NOT NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES sx_qrtz_triggers(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_cron_triggers (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  CRON_EXPRESSION VARCHAR(200) NOT NULL,
  TIME_ZONE_ID VARCHAR(80),
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES sx_qrtz_triggers(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_simprop_triggers (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  STR_PROP_1 VARCHAR(512) NULL,
  STR_PROP_2 VARCHAR(512) NULL,
  STR_PROP_3 VARCHAR(512) NULL,
  INT_PROP_1 INT NULL,
  INT_PROP_2 INT NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC(13,4) NULL,
  DEC_PROP_2 NUMERIC(13,4) NULL,
  BOOL_PROP_1 VARCHAR(1) NULL,
  BOOL_PROP_2 VARCHAR(1) NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES sx_qrtz_triggers(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_blob_triggers (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  BLOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES sx_qrtz_triggers(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_calendars (
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME VARCHAR(200) NOT NULL,
  CALENDAR BLOB NOT NULL,
  PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_paused_trigger_grps (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_fired_triggers (
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR(95) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  FIRED_TIME BIGINT(13) NOT NULL,
  SCHED_TIME BIGINT(13) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE VARCHAR(16) NOT NULL,
  JOB_NAME VARCHAR(200) NULL,
  JOB_GROUP VARCHAR(200) NULL,
  IS_NONCONCURRENT VARCHAR(1) NULL,
  REQUESTS_RECOVERY VARCHAR(1) NULL,
  PRIMARY KEY (SCHED_NAME, ENTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_scheduler_state (
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
  CHECKIN_INTERVAL BIGINT(13) NOT NULL,
  PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sx_qrtz_locks (
  SCHED_NAME VARCHAR(120) NOT NULL,
  LOCK_NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY (SCHED_NAME, LOCK_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
